import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import Footer from '@/components/Footer'
import Summary from '@/components/Summary'
import ScrollToTopButton from '@/components/ScrollToTopButton'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Audiophile | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        {children}
        <Summary />
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  )
}
